### ISSUE TITLE
Expose a flatbread function that handles graphql queries

### ISSUE THREAD

**Issue by odama626** [tonyketcham/flatbread#28]
As a user I want to be able to import a function into a node process and use it to execute graphql queries.

This will enable using flatbread without the need to run a web server in frameworks that support server side functionality

```js
// server side code
import flatbread from 'flatbread'

const query = 'query PostCategory { }'

const data = await flatbread(query)
```

allowing this would let people use flatbread in a getServerSideProps function in nextjs or a routes/endpoint.ts file in sveltekit inside a get() function, or in a similar way in remix, vue etc, and using it this way in theory wouldn't need the apollo dependency since we would just be doing the gql query directly through the function and not with a graphql server.

this may require an internal caching system since the current implementation relies on apollo's cache

**Comment by tonyketcham** [comment]
This is a great differentiator that'll be really useful for ecosystem integration!

**Comment by tonyketcham** [comment]
Tangentially related, I wonder if this strategy could be used to solve #9. I think you're really onto something powerful with this.

I've been wondering if we could convert a filter into a GraphQL subquery that's fully resolved within a root-level resolver that returns a set of matching nodes satisfying the filter
